plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
plugins.security.ssl.transport.pemkey_filepath: esnode-key.pem
plugins.security.ssl.http.pemkey_filepath: esnode-key.pem
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.ssl.transport.pemcert_filepath: esnode.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
plugins.security.ssl.http.enabled: false
plugins.security.ssl.http.pemcert_filepath: esnode.pem
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.system_indices.enabled: true
plugins.security.allow_unsafe_democertificates: true
plugins.security.allow_default_init_securityindex: true
plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem
plugins.security.authcz.admin_dn: CN=kirk,OU=client,O=client,L=test,C=de
plugins.security.audit.type: internal_opensearch
cluster.name: remoteIntegTestWithSecurity
discovery.seed_providers: file
http.port: 0
cluster.routing.allocation.disk.watermark.low: 1b
cluster.routing.allocation.disk.watermark.high: 1b
indices.breaker.total.use_real_memory: false
discovery.seed_hosts: []
path.logs: D:\a\sql\sql\integ-test\build\testclusters\remoteIntegTestWithSecurity-0\logs
path.repo: D:\a\sql\sql\integ-test\build\testclusters\remoteIntegTestWithSecurity-0\repo
script.disable_max_compilations_rate: true
transport.port: 0
path.data: D:\a\sql\sql\integ-test\build\testclusters\remoteIntegTestWithSecurity-0\data
cluster.routing.allocation.disk.watermark.flood_stage: 1b
path.shared_data: D:\a\sql\sql\integ-test\build\testclusters\remoteIntegTestWithSecurity-0\sharedData
node.name: remoteIntegTestWithSecurity-0
node.attr.testattr: test
discovery.initial_state_timeout: 0s
cluster.initial_cluster_manager_nodes: [remoteIntegTestWithSecurity-0]
node.portsfile: true